services:
  database:
    image: postgres:16-alpine
    container_name: opentabletop_database
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./database/.env
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: opentabletop_frontend
    ports:
      - "80:80"
      - "443:443" # <--------- Expose port 443 only if you have a SSL certificate
    volumes:
      - /etc/letsencrypt/live/your.domain.com:/etc/certs/your.domain.com/:ro # <--------- Replace with the location of your certificate. Right part must correspond to the path indicated in nginx.prod.ssl.conf for the certificates
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - database
    networks:
      - app

  backend:
    build:
      context: ./backend
    container_name: opentabletop_backend
    volumes:
      - storage:/app/storage
    depends_on:
      - database
    networks:
      - app

networks:
  app:

volumes:
  postgresql_data:
  storage: