services:
  database:
    image: postgres:16-alpine
    container_name: opentabletop_database
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    networks:
      - app

  frontend:
    build:
      context: ./frontend
    container_name: opentabletop_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - database
    networks:
      - app

  backend:
    build:
      context: ./backend
    container_name: opentabletop_backend
    volumes:
      - storage:/app/storage
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app

networks:
  app:

volumes:
  postgresql_data:
  storage: